(() => {
  'use strict';
  const SITE_URL='https://moufang.xyz/#/music';
  const SUPPORTED=['.mflac','.mgg','.qmc0','.qmc2','.qmc3','.qmcflac','.qmcogg','.tkm','.bkcmp3','.bkcflac','.tm0','.tm2','.tm3','.tm6'];
  const $=id=>document.getElementById(id),dropZone=$('dropZone'),fileInput=$('fileInput'),chooseBtn=$('chooseBtn'),ekeyInput=$('ekeyInput'),results=$('results'),emptyState=$('emptyState'),clearBtn=$('clearBtn');
  const objectUrls=new Set();
  const getExt=name=>SUPPORTED.slice().sort((a,b)=>b.length-a.length).find(ext=>String(name||'').toLowerCase().endsWith(ext))||'';
  const baseName=name=>{const ext=getExt(name);return ext?name.slice(0,-ext.length):name};
  const escapeHtml=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  function addCard(file){emptyState.hidden=true;const el=document.createElement('article');el.className='result';el.innerHTML=`<div class="result-main"><div class="result-name">${escapeHtml(file.name)}</div><div class="result-meta status-work">等待处理…</div></div><div class="action"></div>`;results.prepend(el);return el}
  function setStatus(card,text,kind){const meta=card.querySelector('.result-meta');meta.textContent=text;meta.className=`result-meta ${kind||''}`}
  function setAction(card,html){card.querySelector('.action').innerHTML=html}
  async function processFile(file){const card=addCard(file);if(!getExt(file.name)){setStatus(card,'不支持的文件格式','status-error');return}if(!window.ClaudeOneQQDecrypt){setStatus(card,'解密引擎加载失败，请检查网络后刷新页面','status-error');return}try{setStatus(card,'正在读取文件…','status-work');const buffer=await file.arrayBuffer();const tail=window.ClaudeOneQQDecrypt.parseFileTail(buffer);if(!tail)throw new Error('无法识别 QQ 音乐加密文件');let ekey='';if(tail.format==='musicex'){ekey=ekeyInput.value.trim();if(!ekey){setStatus(card,'检测到新版 musicex：需要对应歌曲的 EKey；可使用网站完整版通过有权限的 QQ 音乐账号获取','status-error');setAction(card,`<a class="full-version" href="${SITE_URL}" target="_blank" rel="noreferrer">打开完整版 ↗</a>`);return}}setStatus(card,`正在解锁 · ${tail.format}`,'status-work');const out=window.ClaudeOneQQDecrypt.decrypt(buffer,ekey||undefined);if(!out?.audio?.byteLength)throw new Error('解锁器没有返回有效音频');const outputExt=String(out.ext||'.mp3').replace(/^\./,''),filename=`${baseName(file.name)}.${outputExt}`,blob=new Blob([out.audio],{type:'application/octet-stream'}),url=URL.createObjectURL(blob);objectUrls.add(url);setStatus(card,`完成 · ${out.format||tail.format} · ${(out.audio.byteLength/1024/1024).toFixed(1)} MB`,'status-ok');setAction(card,`<a class="download" href="${url}" download="${escapeHtml(filename)}">下载 .${escapeHtml(outputExt)}</a>`)}catch(error){console.error(error);setStatus(card,error?.message||'解锁失败','status-error');setAction(card,`<a class="full-version" href="${SITE_URL}" target="_blank" rel="noreferrer">尝试网站完整版 ↗</a>`)}}
  async function handleFiles(list){for(const file of [...list])await processFile(file)}
  chooseBtn.addEventListener('click',e=>{e.stopPropagation();fileInput.click()});dropZone.addEventListener('click',()=>fileInput.click());dropZone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')fileInput.click()});fileInput.addEventListener('change',()=>{handleFiles(fileInput.files);fileInput.value=''});['dragenter','dragover'].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.add('is-over')}));['dragleave','drop'].forEach(type=>dropZone.addEventListener(type,e=>{e.preventDefault();dropZone.classList.remove('is-over')}));dropZone.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length)handleFiles(e.dataTransfer.files)});clearBtn.addEventListener('click',()=>{for(const url of objectUrls)URL.revokeObjectURL(url);objectUrls.clear();results.innerHTML='';emptyState.hidden=false});
})();